alias alt-tab-off="gsettings set org.gnome.desktop.wm.keybindings switch-windows \"['<Super>Tab']\""
alias alt-tab-on="gsettings set org.gnome.desktop.wm.keybindings switch-windows \"['<Alt>Tab','<Super>Tab']\""
export EDITOR="vim"
export HISTFILESIZE=4096
export HISTSIZE=4096
export HISTTIMEFORMAT="%Y-%m-%d> "
export PATH="$HOME/.local/bin:$HOME/scripts:$PATH"
export PS1="\[\033[38;5;10m\]\h\[$(tput sgr0)\]\[\033[38;5;2m\]>\[$(tput sgr0)\]\[\033[38;5;8m\]\w\$\[$(tput sgr0)\] "
export VISUAL="vim"
