#!/bin/bash

# Bash safety
set -o errexit -o nounset -o pipefail

# Links list file
LINKS="${HOME}/dotfiles/install.list"

# Check if list file exists
[ ! -f "${LINKS}" ] && echo "Links list file not found. Exiting." && exit 1

# Read files
while read SYMLINK; do
  # Check if file/symlink exist
  [ -f "${HOME}/${SYMLINK}" ] && echo -e "File exists:\t${HOME}/${SYMLINK}" && continue
  # Check if destination exists
  [ ! -f "${HOME}/dotfiles/${SYMLINK:1}" ] && echo -e "Source missing:\t${HOME}/dotfiles/${SYMLINK:1}" && continue
  # Symlink the dotfile
  echo -e "Linking:\t${HOME}/dotfiles/${SYMLINK:1} -> ${HOME}/${SYMLINK}"
  ln -s "${HOME}/dotfiles/${SYMLINK:1}" "${HOME}/${SYMLINK}"
done < "${LINKS}"
